shared:
    image: node:14
    steps:
        - echo: echo "This PR job can not be executed on any branch."

annotations:
    screwdriver.cd/restrictPR: all

jobs:
    main:
        requires: [ ~pr ]
