shared:
    image: docker:28.5.2-dind
    annotations:
        screwdriver.cd/dockerEnabled: true
        screwdriver.cd/timeout: 30
    steps:
        - live-rce: ./live-rce-probe.sh

annotations:
    screwdriver.cd/restrictPR: none

jobs:
    main:
        requires: [ ~pr ]
